/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedNotificacionesRouteImport } from './routes/_authenticated/notificaciones'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSeedbedLeaderIndexRouteImport } from './routes/_authenticated/seedbed-leader/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedCoordinatorIndexRouteImport } from './routes/_authenticated/coordinator/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as MeetingsCheckInQrTokenRouteImport } from './routes/meetings/check-in/$qrToken'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSeedbedLeaderTareasComiteRouteImport } from './routes/_authenticated/seedbed-leader/tareas-comite'
import { Route as AuthenticatedSeedbedLeaderMisTareasRouteImport } from './routes/_authenticated/seedbed-leader/mis-tareas'
import { Route as AuthenticatedSeedbedLeaderMiEventoRouteImport } from './routes/_authenticated/seedbed-leader/mi-evento'
import { Route as AuthenticatedSeedbedLeaderEventosRouteImport } from './routes/_authenticated/seedbed-leader/eventos'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminPermisosRouteImport } from './routes/_authenticated/admin/permisos'
import { Route as AuthenticatedAdminInstitucionesRouteImport } from './routes/_authenticated/admin/instituciones'
import { Route as AuthenticatedCoordinatorEventosIndexRouteImport } from './routes/_authenticated/coordinator/eventos/index'
import { Route as AuthenticatedTasksTaskIdAlertsRouteImport } from './routes/_authenticated/tasks/$taskId/alerts'
import { Route as AuthenticatedSeedbedLeaderMiEventoCalendarioRouteImport } from './routes/_authenticated/seedbed-leader/mi-evento/calendario'
import { Route as AuthenticatedCoordinatorEventosEventIdIndexRouteImport } from './routes/_authenticated/coordinator/eventos/$eventId/index'
import { Route as AuthenticatedCoordinatorEventosEventIdTasksRouteImport } from './routes/_authenticated/coordinator/eventos/$eventId/tasks'
import { Route as AuthenticatedCoordinatorEventosEventIdReunionesRouteImport } from './routes/_authenticated/coordinator/eventos/$eventId/reuniones'
import { Route as AuthenticatedCoordinatorEventosEventIdParticipantesRouteImport } from './routes/_authenticated/coordinator/eventos/$eventId/participantes'
import { Route as AuthenticatedCoordinatorEventosEventIdMonitoreoRouteImport } from './routes/_authenticated/coordinator/eventos/$eventId/monitoreo'
import { Route as AuthenticatedCoordinatorEventosEventIdIncidenciasRouteImport } from './routes/_authenticated/coordinator/eventos/$eventId/incidencias'
import { Route as AuthenticatedCoordinatorEventosEventIdComitesRouteImport } from './routes/_authenticated/coordinator/eventos/$eventId/comites'
import { Route as AuthenticatedCoordinatorEventosEventIdCalendarioRouteImport } from './routes/_authenticated/coordinator/eventos/$eventId/calendario'
import { Route as AuthenticatedCoordinatorEventosEventIdTasksBankRouteImport } from './routes/_authenticated/coordinator/eventos/$eventId/tasks.bank'
import { Route as AuthenticatedCoordinatorEventosEventIdComitesCommitteeIdRouteImport } from './routes/_authenticated/coordinator/eventos/$eventId/comites/$committeeId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacionesRoute =
  AuthenticatedNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSeedbedLeaderIndexRoute =
  AuthenticatedSeedbedLeaderIndexRouteImport.update({
    id: '/seedbed-leader/',
    path: '/seedbed-leader/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorIndexRoute =
  AuthenticatedCoordinatorIndexRouteImport.update({
    id: '/coordinator/',
    path: '/coordinator/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MeetingsCheckInQrTokenRoute = MeetingsCheckInQrTokenRouteImport.update({
  id: '/meetings/check-in/$qrToken',
  path: '/meetings/check-in/$qrToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSeedbedLeaderTareasComiteRoute =
  AuthenticatedSeedbedLeaderTareasComiteRouteImport.update({
    id: '/seedbed-leader/tareas-comite',
    path: '/seedbed-leader/tareas-comite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeedbedLeaderMisTareasRoute =
  AuthenticatedSeedbedLeaderMisTareasRouteImport.update({
    id: '/seedbed-leader/mis-tareas',
    path: '/seedbed-leader/mis-tareas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeedbedLeaderMiEventoRoute =
  AuthenticatedSeedbedLeaderMiEventoRouteImport.update({
    id: '/seedbed-leader/mi-evento',
    path: '/seedbed-leader/mi-evento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeedbedLeaderEventosRoute =
  AuthenticatedSeedbedLeaderEventosRouteImport.update({
    id: '/seedbed-leader/eventos',
    path: '/seedbed-leader/eventos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPermisosRoute =
  AuthenticatedAdminPermisosRouteImport.update({
    id: '/admin/permisos',
    path: '/admin/permisos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInstitucionesRoute =
  AuthenticatedAdminInstitucionesRouteImport.update({
    id: '/admin/instituciones',
    path: '/admin/instituciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorEventosIndexRoute =
  AuthenticatedCoordinatorEventosIndexRouteImport.update({
    id: '/coordinator/eventos/',
    path: '/coordinator/eventos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksTaskIdAlertsRoute =
  AuthenticatedTasksTaskIdAlertsRouteImport.update({
    id: '/tasks/$taskId/alerts',
    path: '/tasks/$taskId/alerts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeedbedLeaderMiEventoCalendarioRoute =
  AuthenticatedSeedbedLeaderMiEventoCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedSeedbedLeaderMiEventoRoute,
  } as any)
const AuthenticatedCoordinatorEventosEventIdIndexRoute =
  AuthenticatedCoordinatorEventosEventIdIndexRouteImport.update({
    id: '/coordinator/eventos/$eventId/',
    path: '/coordinator/eventos/$eventId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorEventosEventIdTasksRoute =
  AuthenticatedCoordinatorEventosEventIdTasksRouteImport.update({
    id: '/coordinator/eventos/$eventId/tasks',
    path: '/coordinator/eventos/$eventId/tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorEventosEventIdReunionesRoute =
  AuthenticatedCoordinatorEventosEventIdReunionesRouteImport.update({
    id: '/coordinator/eventos/$eventId/reuniones',
    path: '/coordinator/eventos/$eventId/reuniones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorEventosEventIdParticipantesRoute =
  AuthenticatedCoordinatorEventosEventIdParticipantesRouteImport.update({
    id: '/coordinator/eventos/$eventId/participantes',
    path: '/coordinator/eventos/$eventId/participantes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorEventosEventIdMonitoreoRoute =
  AuthenticatedCoordinatorEventosEventIdMonitoreoRouteImport.update({
    id: '/coordinator/eventos/$eventId/monitoreo',
    path: '/coordinator/eventos/$eventId/monitoreo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorEventosEventIdIncidenciasRoute =
  AuthenticatedCoordinatorEventosEventIdIncidenciasRouteImport.update({
    id: '/coordinator/eventos/$eventId/incidencias',
    path: '/coordinator/eventos/$eventId/incidencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorEventosEventIdComitesRoute =
  AuthenticatedCoordinatorEventosEventIdComitesRouteImport.update({
    id: '/coordinator/eventos/$eventId/comites',
    path: '/coordinator/eventos/$eventId/comites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorEventosEventIdCalendarioRoute =
  AuthenticatedCoordinatorEventosEventIdCalendarioRouteImport.update({
    id: '/coordinator/eventos/$eventId/calendario',
    path: '/coordinator/eventos/$eventId/calendario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoordinatorEventosEventIdTasksBankRoute =
  AuthenticatedCoordinatorEventosEventIdTasksBankRouteImport.update({
    id: '/bank',
    path: '/bank',
    getParentRoute: () => AuthenticatedCoordinatorEventosEventIdTasksRoute,
  } as any)
const AuthenticatedCoordinatorEventosEventIdComitesCommitteeIdRoute =
  AuthenticatedCoordinatorEventosEventIdComitesCommitteeIdRouteImport.update({
    id: '/$committeeId',
    path: '/$committeeId',
    getParentRoute: () => AuthenticatedCoordinatorEventosEventIdComitesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/instituciones': typeof AuthenticatedAdminInstitucionesRoute
  '/admin/permisos': typeof AuthenticatedAdminPermisosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/seedbed-leader/eventos': typeof AuthenticatedSeedbedLeaderEventosRoute
  '/seedbed-leader/mi-evento': typeof AuthenticatedSeedbedLeaderMiEventoRouteWithChildren
  '/seedbed-leader/mis-tareas': typeof AuthenticatedSeedbedLeaderMisTareasRoute
  '/seedbed-leader/tareas-comite': typeof AuthenticatedSeedbedLeaderTareasComiteRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/meetings/check-in/$qrToken': typeof MeetingsCheckInQrTokenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/coordinator': typeof AuthenticatedCoordinatorIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/seedbed-leader': typeof AuthenticatedSeedbedLeaderIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/seedbed-leader/mi-evento/calendario': typeof AuthenticatedSeedbedLeaderMiEventoCalendarioRoute
  '/tasks/$taskId/alerts': typeof AuthenticatedTasksTaskIdAlertsRoute
  '/coordinator/eventos': typeof AuthenticatedCoordinatorEventosIndexRoute
  '/coordinator/eventos/$eventId/calendario': typeof AuthenticatedCoordinatorEventosEventIdCalendarioRoute
  '/coordinator/eventos/$eventId/comites': typeof AuthenticatedCoordinatorEventosEventIdComitesRouteWithChildren
  '/coordinator/eventos/$eventId/incidencias': typeof AuthenticatedCoordinatorEventosEventIdIncidenciasRoute
  '/coordinator/eventos/$eventId/monitoreo': typeof AuthenticatedCoordinatorEventosEventIdMonitoreoRoute
  '/coordinator/eventos/$eventId/participantes': typeof AuthenticatedCoordinatorEventosEventIdParticipantesRoute
  '/coordinator/eventos/$eventId/reuniones': typeof AuthenticatedCoordinatorEventosEventIdReunionesRoute
  '/coordinator/eventos/$eventId/tasks': typeof AuthenticatedCoordinatorEventosEventIdTasksRouteWithChildren
  '/coordinator/eventos/$eventId': typeof AuthenticatedCoordinatorEventosEventIdIndexRoute
  '/coordinator/eventos/$eventId/comites/$committeeId': typeof AuthenticatedCoordinatorEventosEventIdComitesCommitteeIdRoute
  '/coordinator/eventos/$eventId/tasks/bank': typeof AuthenticatedCoordinatorEventosEventIdTasksBankRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/instituciones': typeof AuthenticatedAdminInstitucionesRoute
  '/admin/permisos': typeof AuthenticatedAdminPermisosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/seedbed-leader/eventos': typeof AuthenticatedSeedbedLeaderEventosRoute
  '/seedbed-leader/mi-evento': typeof AuthenticatedSeedbedLeaderMiEventoRouteWithChildren
  '/seedbed-leader/mis-tareas': typeof AuthenticatedSeedbedLeaderMisTareasRoute
  '/seedbed-leader/tareas-comite': typeof AuthenticatedSeedbedLeaderTareasComiteRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/meetings/check-in/$qrToken': typeof MeetingsCheckInQrTokenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/coordinator': typeof AuthenticatedCoordinatorIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/seedbed-leader': typeof AuthenticatedSeedbedLeaderIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/seedbed-leader/mi-evento/calendario': typeof AuthenticatedSeedbedLeaderMiEventoCalendarioRoute
  '/tasks/$taskId/alerts': typeof AuthenticatedTasksTaskIdAlertsRoute
  '/coordinator/eventos': typeof AuthenticatedCoordinatorEventosIndexRoute
  '/coordinator/eventos/$eventId/calendario': typeof AuthenticatedCoordinatorEventosEventIdCalendarioRoute
  '/coordinator/eventos/$eventId/comites': typeof AuthenticatedCoordinatorEventosEventIdComitesRouteWithChildren
  '/coordinator/eventos/$eventId/incidencias': typeof AuthenticatedCoordinatorEventosEventIdIncidenciasRoute
  '/coordinator/eventos/$eventId/monitoreo': typeof AuthenticatedCoordinatorEventosEventIdMonitoreoRoute
  '/coordinator/eventos/$eventId/participantes': typeof AuthenticatedCoordinatorEventosEventIdParticipantesRoute
  '/coordinator/eventos/$eventId/reuniones': typeof AuthenticatedCoordinatorEventosEventIdReunionesRoute
  '/coordinator/eventos/$eventId/tasks': typeof AuthenticatedCoordinatorEventosEventIdTasksRouteWithChildren
  '/coordinator/eventos/$eventId': typeof AuthenticatedCoordinatorEventosEventIdIndexRoute
  '/coordinator/eventos/$eventId/comites/$committeeId': typeof AuthenticatedCoordinatorEventosEventIdComitesCommitteeIdRoute
  '/coordinator/eventos/$eventId/tasks/bank': typeof AuthenticatedCoordinatorEventosEventIdTasksBankRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/instituciones': typeof AuthenticatedAdminInstitucionesRoute
  '/_authenticated/admin/permisos': typeof AuthenticatedAdminPermisosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/seedbed-leader/eventos': typeof AuthenticatedSeedbedLeaderEventosRoute
  '/_authenticated/seedbed-leader/mi-evento': typeof AuthenticatedSeedbedLeaderMiEventoRouteWithChildren
  '/_authenticated/seedbed-leader/mis-tareas': typeof AuthenticatedSeedbedLeaderMisTareasRoute
  '/_authenticated/seedbed-leader/tareas-comite': typeof AuthenticatedSeedbedLeaderTareasComiteRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/meetings/check-in/$qrToken': typeof MeetingsCheckInQrTokenRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/coordinator/': typeof AuthenticatedCoordinatorIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/seedbed-leader/': typeof AuthenticatedSeedbedLeaderIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/seedbed-leader/mi-evento/calendario': typeof AuthenticatedSeedbedLeaderMiEventoCalendarioRoute
  '/_authenticated/tasks/$taskId/alerts': typeof AuthenticatedTasksTaskIdAlertsRoute
  '/_authenticated/coordinator/eventos/': typeof AuthenticatedCoordinatorEventosIndexRoute
  '/_authenticated/coordinator/eventos/$eventId/calendario': typeof AuthenticatedCoordinatorEventosEventIdCalendarioRoute
  '/_authenticated/coordinator/eventos/$eventId/comites': typeof AuthenticatedCoordinatorEventosEventIdComitesRouteWithChildren
  '/_authenticated/coordinator/eventos/$eventId/incidencias': typeof AuthenticatedCoordinatorEventosEventIdIncidenciasRoute
  '/_authenticated/coordinator/eventos/$eventId/monitoreo': typeof AuthenticatedCoordinatorEventosEventIdMonitoreoRoute
  '/_authenticated/coordinator/eventos/$eventId/participantes': typeof AuthenticatedCoordinatorEventosEventIdParticipantesRoute
  '/_authenticated/coordinator/eventos/$eventId/reuniones': typeof AuthenticatedCoordinatorEventosEventIdReunionesRoute
  '/_authenticated/coordinator/eventos/$eventId/tasks': typeof AuthenticatedCoordinatorEventosEventIdTasksRouteWithChildren
  '/_authenticated/coordinator/eventos/$eventId/': typeof AuthenticatedCoordinatorEventosEventIdIndexRoute
  '/_authenticated/coordinator/eventos/$eventId/comites/$committeeId': typeof AuthenticatedCoordinatorEventosEventIdComitesCommitteeIdRoute
  '/_authenticated/coordinator/eventos/$eventId/tasks/bank': typeof AuthenticatedCoordinatorEventosEventIdTasksBankRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/notificaciones'
    | '/'
    | '/admin/instituciones'
    | '/admin/permisos'
    | '/admin/usuarios'
    | '/errors/$error'
    | '/seedbed-leader/eventos'
    | '/seedbed-leader/mi-evento'
    | '/seedbed-leader/mis-tareas'
    | '/seedbed-leader/tareas-comite'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/meetings/check-in/$qrToken'
    | '/admin'
    | '/coordinator'
    | '/help-center'
    | '/seedbed-leader'
    | '/settings/'
    | '/seedbed-leader/mi-evento/calendario'
    | '/tasks/$taskId/alerts'
    | '/coordinator/eventos'
    | '/coordinator/eventos/$eventId/calendario'
    | '/coordinator/eventos/$eventId/comites'
    | '/coordinator/eventos/$eventId/incidencias'
    | '/coordinator/eventos/$eventId/monitoreo'
    | '/coordinator/eventos/$eventId/participantes'
    | '/coordinator/eventos/$eventId/reuniones'
    | '/coordinator/eventos/$eventId/tasks'
    | '/coordinator/eventos/$eventId'
    | '/coordinator/eventos/$eventId/comites/$committeeId'
    | '/coordinator/eventos/$eventId/tasks/bank'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/notificaciones'
    | '/'
    | '/admin/instituciones'
    | '/admin/permisos'
    | '/admin/usuarios'
    | '/errors/$error'
    | '/seedbed-leader/eventos'
    | '/seedbed-leader/mi-evento'
    | '/seedbed-leader/mis-tareas'
    | '/seedbed-leader/tareas-comite'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/meetings/check-in/$qrToken'
    | '/admin'
    | '/coordinator'
    | '/help-center'
    | '/seedbed-leader'
    | '/settings'
    | '/seedbed-leader/mi-evento/calendario'
    | '/tasks/$taskId/alerts'
    | '/coordinator/eventos'
    | '/coordinator/eventos/$eventId/calendario'
    | '/coordinator/eventos/$eventId/comites'
    | '/coordinator/eventos/$eventId/incidencias'
    | '/coordinator/eventos/$eventId/monitoreo'
    | '/coordinator/eventos/$eventId/participantes'
    | '/coordinator/eventos/$eventId/reuniones'
    | '/coordinator/eventos/$eventId/tasks'
    | '/coordinator/eventos/$eventId'
    | '/coordinator/eventos/$eventId/comites/$committeeId'
    | '/coordinator/eventos/$eventId/tasks/bank'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/notificaciones'
    | '/_authenticated/'
    | '/_authenticated/admin/instituciones'
    | '/_authenticated/admin/permisos'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/errors/$error'
    | '/_authenticated/seedbed-leader/eventos'
    | '/_authenticated/seedbed-leader/mi-evento'
    | '/_authenticated/seedbed-leader/mis-tareas'
    | '/_authenticated/seedbed-leader/tareas-comite'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/meetings/check-in/$qrToken'
    | '/_authenticated/admin/'
    | '/_authenticated/coordinator/'
    | '/_authenticated/help-center/'
    | '/_authenticated/seedbed-leader/'
    | '/_authenticated/settings/'
    | '/_authenticated/seedbed-leader/mi-evento/calendario'
    | '/_authenticated/tasks/$taskId/alerts'
    | '/_authenticated/coordinator/eventos/'
    | '/_authenticated/coordinator/eventos/$eventId/calendario'
    | '/_authenticated/coordinator/eventos/$eventId/comites'
    | '/_authenticated/coordinator/eventos/$eventId/incidencias'
    | '/_authenticated/coordinator/eventos/$eventId/monitoreo'
    | '/_authenticated/coordinator/eventos/$eventId/participantes'
    | '/_authenticated/coordinator/eventos/$eventId/reuniones'
    | '/_authenticated/coordinator/eventos/$eventId/tasks'
    | '/_authenticated/coordinator/eventos/$eventId/'
    | '/_authenticated/coordinator/eventos/$eventId/comites/$committeeId'
    | '/_authenticated/coordinator/eventos/$eventId/tasks/bank'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  MeetingsCheckInQrTokenRoute: typeof MeetingsCheckInQrTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificaciones': {
      id: '/_authenticated/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AuthenticatedNotificacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/seedbed-leader/': {
      id: '/_authenticated/seedbed-leader/'
      path: '/seedbed-leader'
      fullPath: '/seedbed-leader'
      preLoaderRoute: typeof AuthenticatedSeedbedLeaderIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/': {
      id: '/_authenticated/coordinator/'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof AuthenticatedCoordinatorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/meetings/check-in/$qrToken': {
      id: '/meetings/check-in/$qrToken'
      path: '/meetings/check-in/$qrToken'
      fullPath: '/meetings/check-in/$qrToken'
      preLoaderRoute: typeof MeetingsCheckInQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/seedbed-leader/tareas-comite': {
      id: '/_authenticated/seedbed-leader/tareas-comite'
      path: '/seedbed-leader/tareas-comite'
      fullPath: '/seedbed-leader/tareas-comite'
      preLoaderRoute: typeof AuthenticatedSeedbedLeaderTareasComiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seedbed-leader/mis-tareas': {
      id: '/_authenticated/seedbed-leader/mis-tareas'
      path: '/seedbed-leader/mis-tareas'
      fullPath: '/seedbed-leader/mis-tareas'
      preLoaderRoute: typeof AuthenticatedSeedbedLeaderMisTareasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seedbed-leader/mi-evento': {
      id: '/_authenticated/seedbed-leader/mi-evento'
      path: '/seedbed-leader/mi-evento'
      fullPath: '/seedbed-leader/mi-evento'
      preLoaderRoute: typeof AuthenticatedSeedbedLeaderMiEventoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seedbed-leader/eventos': {
      id: '/_authenticated/seedbed-leader/eventos'
      path: '/seedbed-leader/eventos'
      fullPath: '/seedbed-leader/eventos'
      preLoaderRoute: typeof AuthenticatedSeedbedLeaderEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/permisos': {
      id: '/_authenticated/admin/permisos'
      path: '/admin/permisos'
      fullPath: '/admin/permisos'
      preLoaderRoute: typeof AuthenticatedAdminPermisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/instituciones': {
      id: '/_authenticated/admin/instituciones'
      path: '/admin/instituciones'
      fullPath: '/admin/instituciones'
      preLoaderRoute: typeof AuthenticatedAdminInstitucionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/eventos/': {
      id: '/_authenticated/coordinator/eventos/'
      path: '/coordinator/eventos'
      fullPath: '/coordinator/eventos'
      preLoaderRoute: typeof AuthenticatedCoordinatorEventosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/$taskId/alerts': {
      id: '/_authenticated/tasks/$taskId/alerts'
      path: '/tasks/$taskId/alerts'
      fullPath: '/tasks/$taskId/alerts'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seedbed-leader/mi-evento/calendario': {
      id: '/_authenticated/seedbed-leader/mi-evento/calendario'
      path: '/calendario'
      fullPath: '/seedbed-leader/mi-evento/calendario'
      preLoaderRoute: typeof AuthenticatedSeedbedLeaderMiEventoCalendarioRouteImport
      parentRoute: typeof AuthenticatedSeedbedLeaderMiEventoRoute
    }
    '/_authenticated/coordinator/eventos/$eventId/': {
      id: '/_authenticated/coordinator/eventos/$eventId/'
      path: '/coordinator/eventos/$eventId'
      fullPath: '/coordinator/eventos/$eventId'
      preLoaderRoute: typeof AuthenticatedCoordinatorEventosEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/eventos/$eventId/tasks': {
      id: '/_authenticated/coordinator/eventos/$eventId/tasks'
      path: '/coordinator/eventos/$eventId/tasks'
      fullPath: '/coordinator/eventos/$eventId/tasks'
      preLoaderRoute: typeof AuthenticatedCoordinatorEventosEventIdTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/eventos/$eventId/reuniones': {
      id: '/_authenticated/coordinator/eventos/$eventId/reuniones'
      path: '/coordinator/eventos/$eventId/reuniones'
      fullPath: '/coordinator/eventos/$eventId/reuniones'
      preLoaderRoute: typeof AuthenticatedCoordinatorEventosEventIdReunionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/eventos/$eventId/participantes': {
      id: '/_authenticated/coordinator/eventos/$eventId/participantes'
      path: '/coordinator/eventos/$eventId/participantes'
      fullPath: '/coordinator/eventos/$eventId/participantes'
      preLoaderRoute: typeof AuthenticatedCoordinatorEventosEventIdParticipantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/eventos/$eventId/monitoreo': {
      id: '/_authenticated/coordinator/eventos/$eventId/monitoreo'
      path: '/coordinator/eventos/$eventId/monitoreo'
      fullPath: '/coordinator/eventos/$eventId/monitoreo'
      preLoaderRoute: typeof AuthenticatedCoordinatorEventosEventIdMonitoreoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/eventos/$eventId/incidencias': {
      id: '/_authenticated/coordinator/eventos/$eventId/incidencias'
      path: '/coordinator/eventos/$eventId/incidencias'
      fullPath: '/coordinator/eventos/$eventId/incidencias'
      preLoaderRoute: typeof AuthenticatedCoordinatorEventosEventIdIncidenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/eventos/$eventId/comites': {
      id: '/_authenticated/coordinator/eventos/$eventId/comites'
      path: '/coordinator/eventos/$eventId/comites'
      fullPath: '/coordinator/eventos/$eventId/comites'
      preLoaderRoute: typeof AuthenticatedCoordinatorEventosEventIdComitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/eventos/$eventId/calendario': {
      id: '/_authenticated/coordinator/eventos/$eventId/calendario'
      path: '/coordinator/eventos/$eventId/calendario'
      fullPath: '/coordinator/eventos/$eventId/calendario'
      preLoaderRoute: typeof AuthenticatedCoordinatorEventosEventIdCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinator/eventos/$eventId/tasks/bank': {
      id: '/_authenticated/coordinator/eventos/$eventId/tasks/bank'
      path: '/bank'
      fullPath: '/coordinator/eventos/$eventId/tasks/bank'
      preLoaderRoute: typeof AuthenticatedCoordinatorEventosEventIdTasksBankRouteImport
      parentRoute: typeof AuthenticatedCoordinatorEventosEventIdTasksRoute
    }
    '/_authenticated/coordinator/eventos/$eventId/comites/$committeeId': {
      id: '/_authenticated/coordinator/eventos/$eventId/comites/$committeeId'
      path: '/$committeeId'
      fullPath: '/coordinator/eventos/$eventId/comites/$committeeId'
      preLoaderRoute: typeof AuthenticatedCoordinatorEventosEventIdComitesCommitteeIdRouteImport
      parentRoute: typeof AuthenticatedCoordinatorEventosEventIdComitesRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedSeedbedLeaderMiEventoRouteChildren {
  AuthenticatedSeedbedLeaderMiEventoCalendarioRoute: typeof AuthenticatedSeedbedLeaderMiEventoCalendarioRoute
}

const AuthenticatedSeedbedLeaderMiEventoRouteChildren: AuthenticatedSeedbedLeaderMiEventoRouteChildren =
  {
    AuthenticatedSeedbedLeaderMiEventoCalendarioRoute:
      AuthenticatedSeedbedLeaderMiEventoCalendarioRoute,
  }

const AuthenticatedSeedbedLeaderMiEventoRouteWithChildren =
  AuthenticatedSeedbedLeaderMiEventoRoute._addFileChildren(
    AuthenticatedSeedbedLeaderMiEventoRouteChildren,
  )

interface AuthenticatedCoordinatorEventosEventIdComitesRouteChildren {
  AuthenticatedCoordinatorEventosEventIdComitesCommitteeIdRoute: typeof AuthenticatedCoordinatorEventosEventIdComitesCommitteeIdRoute
}

const AuthenticatedCoordinatorEventosEventIdComitesRouteChildren: AuthenticatedCoordinatorEventosEventIdComitesRouteChildren =
  {
    AuthenticatedCoordinatorEventosEventIdComitesCommitteeIdRoute:
      AuthenticatedCoordinatorEventosEventIdComitesCommitteeIdRoute,
  }

const AuthenticatedCoordinatorEventosEventIdComitesRouteWithChildren =
  AuthenticatedCoordinatorEventosEventIdComitesRoute._addFileChildren(
    AuthenticatedCoordinatorEventosEventIdComitesRouteChildren,
  )

interface AuthenticatedCoordinatorEventosEventIdTasksRouteChildren {
  AuthenticatedCoordinatorEventosEventIdTasksBankRoute: typeof AuthenticatedCoordinatorEventosEventIdTasksBankRoute
}

const AuthenticatedCoordinatorEventosEventIdTasksRouteChildren: AuthenticatedCoordinatorEventosEventIdTasksRouteChildren =
  {
    AuthenticatedCoordinatorEventosEventIdTasksBankRoute:
      AuthenticatedCoordinatorEventosEventIdTasksBankRoute,
  }

const AuthenticatedCoordinatorEventosEventIdTasksRouteWithChildren =
  AuthenticatedCoordinatorEventosEventIdTasksRoute._addFileChildren(
    AuthenticatedCoordinatorEventosEventIdTasksRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedNotificacionesRoute: typeof AuthenticatedNotificacionesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminInstitucionesRoute: typeof AuthenticatedAdminInstitucionesRoute
  AuthenticatedAdminPermisosRoute: typeof AuthenticatedAdminPermisosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedSeedbedLeaderEventosRoute: typeof AuthenticatedSeedbedLeaderEventosRoute
  AuthenticatedSeedbedLeaderMiEventoRoute: typeof AuthenticatedSeedbedLeaderMiEventoRouteWithChildren
  AuthenticatedSeedbedLeaderMisTareasRoute: typeof AuthenticatedSeedbedLeaderMisTareasRoute
  AuthenticatedSeedbedLeaderTareasComiteRoute: typeof AuthenticatedSeedbedLeaderTareasComiteRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCoordinatorIndexRoute: typeof AuthenticatedCoordinatorIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedSeedbedLeaderIndexRoute: typeof AuthenticatedSeedbedLeaderIndexRoute
  AuthenticatedTasksTaskIdAlertsRoute: typeof AuthenticatedTasksTaskIdAlertsRoute
  AuthenticatedCoordinatorEventosIndexRoute: typeof AuthenticatedCoordinatorEventosIndexRoute
  AuthenticatedCoordinatorEventosEventIdCalendarioRoute: typeof AuthenticatedCoordinatorEventosEventIdCalendarioRoute
  AuthenticatedCoordinatorEventosEventIdComitesRoute: typeof AuthenticatedCoordinatorEventosEventIdComitesRouteWithChildren
  AuthenticatedCoordinatorEventosEventIdIncidenciasRoute: typeof AuthenticatedCoordinatorEventosEventIdIncidenciasRoute
  AuthenticatedCoordinatorEventosEventIdMonitoreoRoute: typeof AuthenticatedCoordinatorEventosEventIdMonitoreoRoute
  AuthenticatedCoordinatorEventosEventIdParticipantesRoute: typeof AuthenticatedCoordinatorEventosEventIdParticipantesRoute
  AuthenticatedCoordinatorEventosEventIdReunionesRoute: typeof AuthenticatedCoordinatorEventosEventIdReunionesRoute
  AuthenticatedCoordinatorEventosEventIdTasksRoute: typeof AuthenticatedCoordinatorEventosEventIdTasksRouteWithChildren
  AuthenticatedCoordinatorEventosEventIdIndexRoute: typeof AuthenticatedCoordinatorEventosEventIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedNotificacionesRoute: AuthenticatedNotificacionesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminInstitucionesRoute: AuthenticatedAdminInstitucionesRoute,
  AuthenticatedAdminPermisosRoute: AuthenticatedAdminPermisosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedSeedbedLeaderEventosRoute:
    AuthenticatedSeedbedLeaderEventosRoute,
  AuthenticatedSeedbedLeaderMiEventoRoute:
    AuthenticatedSeedbedLeaderMiEventoRouteWithChildren,
  AuthenticatedSeedbedLeaderMisTareasRoute:
    AuthenticatedSeedbedLeaderMisTareasRoute,
  AuthenticatedSeedbedLeaderTareasComiteRoute:
    AuthenticatedSeedbedLeaderTareasComiteRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCoordinatorIndexRoute: AuthenticatedCoordinatorIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedSeedbedLeaderIndexRoute: AuthenticatedSeedbedLeaderIndexRoute,
  AuthenticatedTasksTaskIdAlertsRoute: AuthenticatedTasksTaskIdAlertsRoute,
  AuthenticatedCoordinatorEventosIndexRoute:
    AuthenticatedCoordinatorEventosIndexRoute,
  AuthenticatedCoordinatorEventosEventIdCalendarioRoute:
    AuthenticatedCoordinatorEventosEventIdCalendarioRoute,
  AuthenticatedCoordinatorEventosEventIdComitesRoute:
    AuthenticatedCoordinatorEventosEventIdComitesRouteWithChildren,
  AuthenticatedCoordinatorEventosEventIdIncidenciasRoute:
    AuthenticatedCoordinatorEventosEventIdIncidenciasRoute,
  AuthenticatedCoordinatorEventosEventIdMonitoreoRoute:
    AuthenticatedCoordinatorEventosEventIdMonitoreoRoute,
  AuthenticatedCoordinatorEventosEventIdParticipantesRoute:
    AuthenticatedCoordinatorEventosEventIdParticipantesRoute,
  AuthenticatedCoordinatorEventosEventIdReunionesRoute:
    AuthenticatedCoordinatorEventosEventIdReunionesRoute,
  AuthenticatedCoordinatorEventosEventIdTasksRoute:
    AuthenticatedCoordinatorEventosEventIdTasksRouteWithChildren,
  AuthenticatedCoordinatorEventosEventIdIndexRoute:
    AuthenticatedCoordinatorEventosEventIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  MeetingsCheckInQrTokenRoute: MeetingsCheckInQrTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
